[legacy_capture]
testVM1 ansible_host=192.168.122.236 nt_capture_iface=eth0
testVM2 ansible_host=192.168.122.237 nt_capture_iface=eth1

[legacy_capture:vars]
ansible_user=root
ansible_password=qaz123
