---
- name: Deploy NetworkTracing Legacy Agent to Fleet
  hosts: legacy_capture
  gather_facts: false
  become: true
  serial: "100%"
  max_fail_percentage: 10

  roles:
    - role: networktracing_legacy
